version: '3.9'
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dostavim
    ports:
      - 3306:3306
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d/
  web:
    build: ./DostavimVse
    depends_on:
      - db
    links:
      - db:db
    ports:
      - 8080:8080
    expose:
      - 8080
# networks:
#   dostavimvse-net:
#     name: custom_dostavimvse_net
#     driver: bridge

# docker run --rm -it -e MYSQL_ROOT_PASSWORD=admin -e MYSQL_DATABASE=dostavim -v scripts:/docker-entrypoint-initdb.d/ -p 3306:3306 mysql:5.7