# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [task5]

jobs:
  Configure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.x'

      # Runs a single command using the runners shell
      - name: Build
        run: |
          cd task5
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
          cmake --build .
          cmake --install .

      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          exec-path: bin/CTestExe
          report-path: report.xml
          working-directory: task5

      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distributive
          path: |
            task5/install/exe
