# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [task5]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.16.x'

      # Runs a single command using the runners shell
      - name: Run cmake
        run: |
          cd task5
          mkdir build
          cd build
          cmake ..
          cmake --build .
          cd ..
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: current-build
          path: |
            ./bin
            ./lib

  # Test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo "I'm testing now"

  #     - name: Akht script doing
  #       uses: akhtyamovpavel/ActionGtestReport@v0.0.9
